// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvmwcgnlebbesarvsvxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12bXdjZ25sZWJiZXNhcnZzdnhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMTc4NzksImV4cCI6MjA3Mjc5Mzg3OX0.OrQkQdGWmLNPCAYsjiRknXBUEsuegMS82-3b2D2g5ik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});